### ISSUE TITLE
Hello Guys

### ISSUE THREAD

**Issue by Balgor18** [SongSongPaPa/learn_nest#7]
Take care you have your 42 API Key accesible for erveryone. Move it in private pls.

**Comment by Zekao** [comment]
Thanks for your API Key, I will make a good usage of it

**Comment by KOREAparksh** [comment]
@Balgor18 @Zekao 
Thanks. I uploaded it without thinking while practicing. ~~It is currently deleted~~ It's currently disabled. I will take good care of key and token in the future.
